version: "3.2"
services:
    mvc-web:
        build: .
        container_name: mvc
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"
        ports:
            - "8080:5000"
        depends_on:
            - db
        networks:
            - linuxaspnetcore
        restart: unless-stopped
    db:
        image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
        container_name: mvc-db
        restart: always
        environment:
            MSSQL_SA_PASSWORD: "3XSsBjPkcnfR"
            SA_PASSWORD: "3XSsBjPkcnfR"
            ACCEPT_EULA: "Y"
        ports:
            - "1433"
        volumes:
            - linuxaspnetcoredata:/var/opt/mssql
        networks:
            - linuxaspnetcore

volumes:
    linuxaspnetcoredata:

networks:
    linuxaspnetcore:
        driver: bridge
